# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('splash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.Category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splash.Location')),
            ],
        ),
    ]
